version: '3.8'

services:
  frontend:
    build: ./front
    container_name: frontend_service
    ports:
      - '3000:800'
    volumes:
      - ./front:/app
      - /app/node_modules
    stdin_open: true
