version: '3.8'

services:
  frontend:
    build: ./front
    container_name: frontend_service
    ports:
      - '3000:80'
    volumes:
      - ./front:/app
      - /app/node_modules
    stdin_open: true
  backend:
    build:
      context: ./back
    container_name: backend_service
    ports:
      - '3001:3000'
    volumes:
      - ./back/data:/app/data
    environment:
      - NODE_ENV=production
